### ISSUE TITLE
Add support for monospace-styling in Textarea

### ISSUE THREAD

**Issue by elekktrisch** [six-group/six-webcomponents#102]
### What problem does this feature solve?

In some Forms, we'd like to allow for editing code-style text, e.g. JSON. Textarea currently doesn't allow overriding the font-family. The feature could easily be added by defining an additional property which will switch the textarea to font-family monospace.

### What does the proposed API look like?

`<six-textarea textStyle="code"></six-textarea>`

**Comment by colinscz** [comment]
As per this [comment ](https://github.com/six-group/six-webcomponents/pull/103#issuecomment-1736882133) in #102 by @ibirrer 

this can be done by using the [css part pseudo selector](https://developer.mozilla.org/en-US/docs/Web/CSS/::part)

```css 
six-textarea::part(textarea) {
  font-family: monospace;
}
```

Therefore I will close this issue as the existing API provides a solution. In case there is more extensive need for different text styles we would reconsider this in the future.
