### ISSUE TITLE
Favicon not loading on documentation

### ISSUE THREAD

**Issue by davidemarcoli** [six-group/six-webcomponents#109]
### Six Webcomponents version

-

### Steps to reproduce

Go to https://six-group.github.io/six-webcomponents/

### What is expected?

Favicon should be visible

### What is actually happening?

Favicon is not visible
![image](https://github.com/six-group/six-webcomponents/assets/69892203/85a6a2a8-da8b-4294-97b2-3664636dcb39)

### System Info

```shell
Edge: Version 117.0.2045.36 (Offizielles Build) (64-Bit)
Firefox: 113.0.1 (64-bit)
Chrome: Version 116.0.5845.188 (Offizieller Build) (64-Bit)
```

**Comment by Riatomerehentroweard** [comment]
[Fixed with PR #118](https://github.com/six-group/six-webcomponents/pull/118)

I will thus close the ticket
