### ISSUE TITLE
Make hamburger menu optional in six-header

### ISSUE THREAD

**Issue by philippd** [six-group/six-webcomponents#157]
### What problem does this feature solve?

Currently, the `six-header` component includes a hamburger menu by default. While this is useful in most applications, it should be possible to remove the hamburger menu from the header.
For example our "Home" app presents all available applications on a single screen, eliminating the need for additional navigation through a sidebar.

### What does the proposed API look like?

- Introduce a boolean property (e.g., `show-hamburger-menu`) in the `six-header` component.
- This property should default to `true`, preserving current functionality for other applications.
- When set to `false`, the hamburger menu icon should be hidden.

**Comment by stefanrufer** [comment]
Sound reasonable for me - go for it!
