### ISSUE TITLE
SIX-INPUT autocorrect property not working as expected

### ISSUE THREAD

**Issue by tomwilhelm** [six-group/six-webcomponents#159]
### Six Webcomponents version

4

### Steps to reproduce

1. <six-input type="number" min="100" autocorrect="off">
when I use a six input type with those properties I expect that when I input something in the six input, that the value is not getting autocorrected, unfortunately this is not what happening. Probably I misunderstood that autocorrect does, but the Property description is unfortunately not telling me more detailed information of what it does:
"The input's autocorrect attribute."

### What is expected?

After I enter 50 it should **not** autocorrect the value to the min value.

### What is actually happening?

After I enter 50 it is autocorrected to the min value.

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 3.13 GB / 31.72 GB
  Binaries:
    Node: 16.19.0 - C:\develop\bin\node16\node.EXE
    npm: 9.7.1 - C:\develop\bin\node16\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (120.0.2210.77)
    Internet Explorer: 11.0.19041.3636
```

**Comment by davidemarcoli** [comment]
Hi @tomwilhelm 👋 
I'm pretty sure that `autocorrect` is the safari equivalent of `spellcheck`.
(According to mdn web docs: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#autocorrect)

**Comment by tomwilhelm** [comment]
it was a problem with our own component which is wrapping the six-input. sorry
