### ISSUE TITLE
Add data-testid attributes to internal elements to facilitate testing

### ISSUE THREAD

**Issue by franckdervaux** [six-group/six-webcomponents#189]
### What problem does this feature solve?

When one writes tests for a UI using the components, it sometimes requires to access the 'internals' of the component.
An example is the DatePicker. You need to search into the shadowroot for an 'input' element to simulate the user clicking the picker.
Or you need to search using the '.next' css class to get to the button to navigate to the next month.
This makes the tests fragile wrt to changes in the component.

### What does the proposed API look like?

I would suggest to add 'data-testid' attributes to internal elements that could be necessary for testing. These attributes should be documented.

**Comment by colinscz** [comment]
Hi @franckdervaux we considered this option, but for the moment we don't plan to add this to the library. There are other ways to add such test-id attributes directly to the implementation and reference the components. Although we agree that the internal elements should be selectable to execute test scenarios. We will work on improving this in the future.
