### ISSUE TITLE
Sidebar can overflow when text is too long

### ISSUE THREAD

**Issue by davidemarcoli** [six-group/six-webcomponents#192]
### Six Webcomponents version

4.0.4

### Steps to reproduce

Add long text to a sidebar item group

### What is expected?

Either the sidebar should extend automatically or the text should wrap

### What is actually happening?

![image](https://github.com/six-group/six-webcomponents/assets/69892203/d029fa7a-10e7-42c4-b90d-e030637feaa8)

**Comment by stefanlaux** [comment]
fax
