### ISSUE TITLE
filter option does not work on six-select when options are used

### ISSUE THREAD

**Issue by franckdervaux** [six-group/six-webcomponents#193]
### Six Webcomponents version

4.0.4

### Steps to reproduce

(Vue code)
Setup a six-select component providing items through the options prop and setting the filter option.
```typescript
const selectValues = ref([{ value: 'Alpha', label: 'Alpha' }, { value: 'Bravo', label: 'Bravo' }, { value: 'Charlie', label: 'Charlie' }, { value: 'Delta', label: 'Delta' }]);

<six-select v-model="selectValue" label="Select" :options="selectValues" :filter=true placeholder="Select one"
      :disabled="disabled" :invalid="invalid" error-text="Select Error">
    </six-select>
``` 
    
Drop the menu down and enter the beginning of one of the values, for example 'alph'.

### What is expected?

The drop-down should be filtered and only show the matching entries.

### What is actually happening?

Nothing: the whole list is still shown.

### System Info

```shell
Running on Windows 10 Entreprise 22H2, in MS Edge Version 121.0.2277.98 (Official build) (64-bit).
```

**Comment by ibirrer** [comment]
Does it work if you provide the options as `six-menu-item` child elements?

Also, can you try if it works with latest insider relase for Vue: https://www.npmjs.com/package/@six-group/ui-library-vue/v/0.0.0-insider.8112beb?

**Comment by franckdervaux** [comment]
Before upgrading to the latest version, it was not working either with using `six-menu-item` elements.
Note that I have 1395 elements in the dropdown.

After upgrading to the latest version, the issue was still reproducing.
However, when providing the options directly as `six-menu-item`, it is now working.
