### ISSUE TITLE
Icon of the six-select gets selected when double clicking on the select

### ISSUE THREAD

**Issue by davidemarcoli** [six-group/six-webcomponents#223]
### Six Webcomponents version

4.1.2

### Steps to reproduce

double click on a six-select

### What is expected?

Icon not being selected

### What is actually happening?

![image](https://github.com/six-group/six-webcomponents/assets/69892203/863b669c-50a1-44c2-8316-359aad7704d0)

**Comment by stefanrufer** [comment]
@davidemarcoli Please check if it still happens with the newest version 4.2.2

**Comment by stefanrufer** [comment]
Does not happen any more.
