### ISSUE TITLE
Disabled Six Button fires (atleast) click event - even though it should not

### ISSUE THREAD

**Issue by dkraemerwork** [six-group/six-webcomponents#237]
### Six Webcomponents version

4.0.4

### Steps to reproduce

https://github.com/six-group/six-webcomponents/assets/56352124/64f2bee8-b32b-417a-9ee3-7620d791772f

In this case, the router navigation takes place.
In other cases, the click event is sent out.

![image](https://github.com/six-group/six-webcomponents/assets/56352124/aa956955-3f46-47a5-899a-f8c97f7b9941)

### What is expected?

If the button is disabled, it should not be clickable.

### What is actually happening?

The Button is disabled, it still registers clicks or any other events.

### Any additional comments?

Its quite the critical bug since it effects all applications using these buttons.

**Comment by davidemarcoli** [comment]
Fixed in https://github.com/six-group/six-webcomponents/commit/4b2f7697ce4bd83360018cd40e9b091923228946. Please use latest version
