### ISSUE TITLE
Hovering over a selected date in the datepicker makes it unreadable

### ISSUE THREAD

**Issue by davidemarcoli** [six-group/six-webcomponents#238]
### Six Webcomponents version

4.2.2

### Steps to reproduce

Select a date in the datepicker and then hover over it

### What is expected?

The day is still readable

### What is actually happening?

The day isn't readable
![image](https://github.com/six-group/six-webcomponents/assets/69892203/3f19fc1b-89cf-45f3-8ff5-ad4469454162)

### Any additional comments?

The background shouldn't change on hover (same [angular material](https://material.angular.io/components/datepicker/overview))
![image](https://github.com/six-group/six-webcomponents/assets/69892203/2475a474-d510-4094-bcd6-be2910c661ff)

**Comment by stefanrufer** [comment]
Good idea, go for it!

**Comment by stefanrufer** [comment]
Will be fixed with the new implementation of six-date
