### ISSUE TITLE
Add a part to tab-indicator to make it possible to remove it

### ISSUE THREAD

**Issue by tkwe8** [six-group/six-webcomponents#241]
### What problem does this feature solve?

In some places the tab-indicator obstructs certain tables, grids etc. and it would be great to be able to remove it:

![image](https://github.com/six-group/six-webcomponents/assets/167750324/439e58ba-eba9-4b9d-a542-6b9242c83d77)

### What does the proposed API look like?

Make it that something like this works:

```
six-tab-group::part(active-tab-indicator) {
  display: none;
}
```

**Comment by stefanrufer** [comment]
The proposal is fine, we will take this up.
