### ISSUE TITLE
Six Error Page has an issue with custom error descriptions

### ISSUE THREAD

**Issue by colinscz** [six-group/six-webcomponents#262]
### Six Webcomponents version

v4.2.2

### Steps to reproduce

Use a string for the description. String does not support .map function which results in an error when the custom description should be assigned. Should only be executed if the customDescription is in fact a set of strings / an array.

![grafik](https://github.com/six-group/six-webcomponents/assets/19342760/2d3ef353-0f00-4510-96df-f64eb05a9afa)

![grafik](https://github.com/six-group/six-webcomponents/assets/19342760/b893b059-3540-46de-85cf-0cf5a49b9f31)

### What is expected?

- Error Description can be assigned

### What is actually happening?

![grafik](https://github.com/six-group/six-webcomponents/assets/19342760/c02343fe-679e-4bd1-adfb-428bab713c30)

**Comment by stefanrufer** [comment]
Is the string[] shown at all? Example does not look like this. 
Check if the customDescription can be removed in the first place. Custom descriptions could be given with a slot.

**Comment by davidemarcoli** [comment]
> * on customDescription property document that an error code needs to be given.
> * improve the last example to give an error code so that the customDescription is actually shown

@stefanrufer @colinscz 
In dev the description is showing without passing an error code (as it probably should be).
![image](https://github.com/six-group/six-webcomponents/assets/69892203/c422bc16-08c0-42b5-8c7e-814235124c8d)
There is a problem when rendering it in the docs. I'll try to debug it.

**Comment by colinscz** [comment]
@davidemarcoli I fixed this issue on my side. Thank you for the investigation. We can close it.
