### ISSUE TITLE
Datepicker is misaligned with other components

### ISSUE THREAD

**Issue by flamenkito** [six-group/six-webcomponents#265]
### Six Webcomponents version

4.2.2

### Steps to reproduce

```html
<div style="display: flex; gap: 0.5rem">
  <six-datepicker label="Datepicker" style="width: 50%"></six-datepicker>
  <six-input label="Input" style="width: 50%"></six-input>
</div>
```

![image](https://github.com/six-group/six-webcomponents/assets/28656840/4b6332b3-2f80-436a-ab74-b52b46054488)

### What is expected?

![image](https://github.com/six-group/six-webcomponents/assets/28656840/26a5a603-d212-4be6-b455-659fd6e7e604)

### What is actually happening?

Datepicker label takes extra 4px margin-top, could be fixed with an ugly CSS patch
```css
six-datepicker::part(base) {
  margin-top: -4px;
}
```

**Comment by stefan-laux** [comment]
Should be fixed with v4.3.0
