### ISSUE TITLE
Proposal: Multiple error messages

### ISSUE THREAD

**Issue by pennal** [six-group/six-webcomponents#70]
### What problem does this feature solve?

Currently, there is no way to override the slot for the errors or to show multiple errors at the same time. 

### What does the proposed API look like?

Proposal
Two ways to pass an error message
1. __Using a prop on the component__
```js
    <six-input errorText="My awesome error"/>
```
This will render a simple message, in red, under the input field.

```
    +-------------------+
    |                   |
    +-------------------+
    My awesome error
```
You can also provide a list of error messages, and they will all be shown as a list (unstiled):

```
    <six-input errorText="['My awesome error', 'another error']"/>
```
Which will render as
```
    +-------------------+
    |                   |
    +-------------------+
    My awesome error
    another error
```
**Optional**: With the errorTextCount prop you can choose how many error messages are shown:

```js
    <six-input errorText="['My awesome error', 'another error']" errorTextCount="1"/>
```
Which will render as
```
    +-------------------+
    |                   |
    +-------------------+
    My awesome error
    ...
```
Internally, this will use a `six-error` component which is already stiled with the default colors

2. __Using a slot__
By using the `six-error` component, you can then customise the content of the error message(s):
```js
    <six-input>
        <div slot="errors">
            <six-error *ngFor="let error in errors">{{ error.toUpperCase() }}</six-error>
        </div>
    </six-input>
```
Which would render as
```
    +-------------------+
    |                   |
    +-------------------+
    MY AWESOME ERROR
```

**Comment by ibirrer** [comment]
Closed with #88
