### ISSUE TITLE
Fix vulnerable dependencies

### ISSUE THREAD

**Issue by pennal** [six-group/six-webcomponents#76]
### Six Webcomponents version

v4 beta

### Steps to reproduce

`npm install` shows that there are highly vulnerable packages:

```
added 1814 packages, and audited 1843 packages in 1m

285 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

### What is expected?

No vulnerabilities should be included, where possible

### What is actually happening?

There are vulnerabilities

**Comment by pennal** [comment]
After a bit of digging, I believe this is currently not fixable. To narrow down where the issue was, I used `npm audit`, which returned the following:

```
# npm audit report

nth-check  <2.0.1
Severity: high
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
fix available via `npm audit fix --force`
Will install react-scripts@2.1.3, which is a breaking change
node_modules/svgo/node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/svgo/node_modules/css-select
    svgo  1.0.0 - 1.3.2
    Depends on vulnerable versions of css-select
    node_modules/svgo
      @svgr/plugin-svgo  <=5.5.0
      Depends on vulnerable versions of svgo
      node_modules/@svgr/plugin-svgo
        @svgr/webpack  4.0.0 - 5.5.0
        Depends on vulnerable versions of @svgr/plugin-svgo
        node_modules/@svgr/webpack
          react-scripts  >=2.1.4
          Depends on vulnerable versions of @svgr/webpack
          node_modules/react-scripts

6 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

Running `npm audit fix --force` does not help though, so I have found out through the usage of `npm list` that the issue is in a transitive dependency, from the react example app:

```
@six-group/workspace@4.0.0-beta.0 /Users/lucas/Repos/six-webcomponents
├─┬ @six-group/demo-app-angular@0.0.0 -> ./examples/angular
│ └─┬ @angular-devkit/build-angular@15.2.9
│   └─┬ critters@0.0.16
│     └─┬ css-select@4.3.0
│       └── nth-check@2.1.1
└─┬ @six-group/ui-library-react-app@0.1.0 -> ./examples/react
  └─┬ react-scripts@5.0.1
    └─┬ @svgr/webpack@5.5.0
      └─┬ @svgr/plugin-svgo@5.5.0
        └─┬ svgo@1.3.2
          └─┬ css-select@2.1.0
            └── nth-check@1.0.2
```

`nth-check` is being imported from the dependencies of react-scripts, which hasn't had an update in well over a year [https://www.npmjs.com/package/react-scripts](https://www.npmjs.com/package/react-scripts). 

To fix this issue, we would have to upgrade to a breaking changes releases, which I believe is a really bad idea. My suspicion is that it hasn't been updated since react officially [recommends using vite](https://github.com/reactjs/react.dev/pull/5487) to create new apps. Therefore there are two solutions:
1. We stick with the current version, and simply ignore the issues. This may be more of an issue down the road though
2. We nuke the current react example, and create a new one with vite

This is only my opinion, open to other solutions

**Comment by colinscz** [comment]
@ibirrer @pennal the mentioned dependency is removed now. I will therefore close this ticket.
