### ISSUE TITLE
six-tab-group does not update selection bar when size updates

### ISSUE THREAD

**Issue by pennal** [six-group/six-webcomponents#79]
### Six Webcomponents version

v4.0.0-beta

### Steps to reproduce

When the tab width of a tab-group changes, the bar highlighting the current element does not update its position.

We have seen this issue happen when we switch language, and the title of the tab changes its width. Example: 
![MicrosoftTeams-image (1)](https://github.com/six-group/six-webcomponents/assets/8777268/5bfb30ce-397a-43a6-bf92-6928a0a49a07)

To reproduce:
 - Create a six-tab-group
 - Set the highlighted item to any of the items, does not matter
 - Change the width of these items
 - See the bar not update its position

### What is expected?

The bar highlighting the current active item should update its position

### What is actually happening?

The bar is not moving

**Comment by pennal** [comment]
After a bit of digging, I think the issue is in the assumption that the `onSlotChange` event will fire anytime the content changes. According to https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/slotchange_event, this does not happen.

This event is currently used in six-tab-group:347, which calls the sync function that recalculates the position of the bar.

I think this could be solved this way:
1. Attach an event listener for the slot change
2. Whenever the slot content changes, we iterate over all the children and attach an event listener bound to the current sync method

This way, we would get notified if the content of the children passed through the slot changed, and update the position of the bar

**Comment by stefanlaux** [comment]
Hello @ibirrer 

I noticed a small bug with the six-tab-group. Does this fix also resolve this bug?

https://github.com/six-group/six-webcomponents/assets/90751877/a150bdd2-420c-4689-ba55-d52cdc07865f

**Comment by ibirrer** [comment]
> Hello @ibirrer
> 
> I noticed a small bug with the six-tab-group. Does this fix also resolve this bug?
> 
>  2023-08-30.19-11-55.mov

Yes, this should be fixed
